const IC={dash:'<rect x="3" y="3" width="7" height="9"/><rect x="14" y="3" width="7" height="5"/><rect x="14" y="12" width="7" height="9"/><rect x="3" y="16" width="7" height="5"/>',
students:'<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>',
hostels:'<path d="M3 21h18M5 21V7l7-4 7 4v14M9 9h2M13 9h2M9 13h2M13 13h2M10 21v-4h4v4"/>',
rooms:'<path d="M5 21V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v17M3 21h18M15 12h.01"/>',
allocations:'<path d="M7 7h13l-4-4M17 17H4l4 4"/>',payments:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/>',
complaints:'<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',services:'<path d="M12 2l3 7 7 .6-5.3 4.7 1.6 7.2L12 17.8 5.7 21.5l1.6-7.2L2 9.6 9 9z"/>',
plus:'<path d="M12 5v14M5 12h14"/>',eye:'<path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8S1 12 1 12z"/><circle cx="12" cy="12" r="3"/>',
edit:'<path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z"/>',trash:'<path d="M3 6h18M8 6V4h8v2M6 6l1 14h10l1-14"/>',back:'<path d="M19 12H5M12 19l-7-7 7-7"/>',
pay:'<path d="M12 1v22M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>',bed:'<path d="M2 20V6M2 14h20v6M22 14v-3a3 3 0 0 0-3-3h-9v6"/>'};
const ic=n=>`<svg class="i" viewBox="0 0 24 24">${IC[n]}</svg>`;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=d=>d?new Date(d+'T00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—',money=n=>'₹'+Number(n).toLocaleString('en-IN'),today=()=>new Date().toISOString().slice(0,10);
const db={
student:[['STU2023001','Aarav Reddy','Male','9876501234','aarav.reddy@uni.edu','B.Tech','3','Computer Science'],['STU2023014','Rohan Mehta','Male','9876502345','rohan.mehta@uni.edu','B.Tech','3','Mechanical'],['STU2024007','Kiran Patel','Male','9876503456','kiran.patel@uni.edu','B.Sc','2','Physics'],['STU2024019','Ananya Sharma','Female','9876504567','ananya.sharma@uni.edu','B.Tech','2','Electronics'],['STU2024032','Meera Nair','Female','9876505678','meera.nair@uni.edu','BBA','2','Management'],['STU2025003','Daniel Joseph','Male','9876506789','daniel.joseph@uni.edu','M.Tech','1','Civil'],['STU2025011','Sneha Iyer','Female','9876507890','sneha.iyer@uni.edu','B.Com','1','Commerce'],['STU2025026','Imran Khan','Male','9876508901','imran.khan@uni.edu','MCA','1','Computer Applications']].map(a=>Object.fromEntries('student_id,name,gender,phone,email,course,year,department'.split(',').map((k,i)=>[k,a[i]]))),
hostel:[['H01','Aryabhatta Boys Hostel','North Campus','Dr. R. Menon',40],['H02','Sarojini Girls Hostel','East Campus','Mrs. L. Fernandes',36],['H03','Raman Postgraduate Block','South Campus','Dr. S. Verma',30]].map(a=>Object.fromEntries('hostel_id,name,location,warden,capacity'.split(',').map((k,i)=>[k,a[i]]))),
room:[['R001','H01','101','Single',1,'Occupied'],['R002','H01','102','Double',2,'Occupied'],['R003','H01','103','Single',1,'Available'],['R004','H01','104','Triple',3,'Available'],['R005','H02','201','Double',2,'Occupied'],['R006','H02','202','Single',1,'Available'],['R007','H02','203','Single',1,'Maintenance'],['R008','H02','204','Double',2,'Available'],['R009','H03','301','Single',1,'Occupied'],['R010','H03','302','Single',1,'Available'],['R011','H03','303','Double',2,'Available'],['R012','H03','304','Triple',3,'Available']].map(a=>Object.fromEntries('room_id,hostel_id,room_no,type,capacity,status'.split(',').map((k,i)=>[k,a[i]]))),
allocation:[['A001','STU2023001','R001','2026-07-10','2027-05-31','Active'],['A002','STU2023014','R002','2026-07-11','2027-05-31','Active'],['A003','STU2024007','R002','2026-07-12','2027-05-31','Active'],['A004','STU2024019','R005','2026-07-14','2027-05-31','Active'],['A005','STU2024032','R005','2026-07-15','2027-05-31','Active'],['A006','STU2025003','R009','2026-08-01','2027-06-30','Active']].map(a=>Object.fromEntries('alloc_id,student_id,room_id,alloc_date,end_date,status'.split(',').map((k,i)=>[k,a[i]]))),
payment:[['P001','STU2023001',45000,'2026-07-08','UPI','Paid'],['P002','STU2023014',45000,'2026-07-09','Net Banking','Paid'],['P003','STU2024007',45000,'2026-07-12','Cash','Paid'],['P004','STU2024019',48000,'2026-07-13','Card','Paid'],['P005','STU2024032',48000,'2026-09-02','UPI','Pending'],['P006','STU2025003',52000,'2026-08-01','Net Banking','Paid'],['P007','STU2023001',6000,'2026-09-15','UPI','Pending'],['P008','STU2024007',6000,'2026-09-20','Card','Failed']].map(a=>Object.fromEntries('payment_id,student_id,amount,date,mode,status'.split(',').map((k,i)=>[k,a[i]]))),
complaint:[['C001','STU2023014','Plumbing','Water leakage in bathroom tap','2026-09-28','Pending'],['C002','STU2024019','Electrical','Ceiling fan makes loud noise','2026-09-30','In Progress'],['C003','STU2025003','Internet','Wi-Fi drops frequently at night','2026-10-01','Pending'],['C004','STU2023001','Cleanliness','Corridor not cleaned for two days','2026-09-22','Resolved']].map(a=>Object.fromEntries('complaint_id,student_id,type,description,date,status'.split(',').map((k,i)=>[k,a[i]]))),
service:[['SV001','H01','Laundry','Coin-operated machines, ground floor',1],['SV002','H01','Wi-Fi','High-speed campus network',1],['SV003','H01','Gym','Weights and cardio, 6 am – 9 pm',1],['SV004','H02','Housekeeping','Daily room and corridor cleaning',1],['SV005','H02','Drinking Water','RO purified water on every floor',1],['SV006','H02','Laundry','Machine under maintenance',0],['SV007','H03','Maintenance','24×7 electrical and plumbing desk',1],['SV008','H03','Wi-Fi','Fibre connection in all rooms',1]].map(a=>({service_id:a[0],hostel_id:a[1],name:a[2],description:a[3],available:a[4]?'Available':'Unavailable'}))};
const A=(t,k,v)=>db[t].find(x=>x[k]==v),nid=(t,k,p,n=3)=>p+String(Math.max(0,...db[t].map(x=>+x[k].replace(/\D/g,'')))+1).padStart(n,'0');
const occ=r=>db.allocation.filter(a=>a.room_id==r&&a.status=='Active').length,hocc=h=>db.room.filter(r=>r.hostel_id==h).reduce((s,r)=>s+occ(r.room_id),0);
const sync=id=>{const r=A('room','room_id',id);if(r&&r.status!='Maintenance')r.status=occ(id)>=r.capacity?'Occupied':'Available'};
const sn=id=>A('student','student_id',id)?.name||id,rl=id=>{const r=A('room','room_id',id);return r?`${A('hostel','hostel_id',r.hostel_id)?.name} – ${r.room_no}`:id};
const BM={Paid:'ok',Available:'ok',Resolved:'ok',Active:'ok',Pending:'wn','In Progress':'wn',Reserved:'wn',Failed:'bd',Maintenance:'bd',Unavailable:'bd',Occupied:'inf',Completed:'gy'};
const bg=s=>`<span class="bg ${BM[s]||'gy'}">${esc(s)}</span>`;
function toast(m,e){const d=document.createElement('div');d.className='toast'+(e?' err':'');d.textContent=m;$('#t').append(d);setTimeout(()=>d.remove(),3200)}
const closeM=()=>$('#m').innerHTML='';
function fld(f,v){const val=v?.[f.n]??f.d??'';let i;
if(f.t=='select')i=`<select name="${f.n}" ${f.ch?`onchange="${f.ch}"`:''}>${f.o.map(o=>{const[a,b]=Array.isArray(o)?o:[o,o];return`<option value="${esc(a)}" ${a==val?'selected':''}>${esc(b)}</option>`}).join('')}</select>`;
else if(f.t=='textarea')i=`<textarea name="${f.n}" rows="3" required>${esc(val)}</textarea>`;
else i=`<input name="${f.n}" type="${f.t||'text'}" value="${esc(val)}" required ${f.ro?'readonly':''} ${f.t=='number'?'min="1"':''}>`;
return`<label class="${f.w?'w2':''}"><span>${f.l}</span>${i}</label>`}
function modal(title,fields,vals,btn,save){$('#m').innerHTML=`<div class="ov" onmousedown="if(event.target==this)closeM()"><form class="md"><h3>${title}</h3><div class="fg">${fields.map(f=>fld(f,vals)).join('')}</div><div class="ft"><button type="button" class="b g" onclick="closeM()">Cancel</button><button class="b p">${btn}</button></div></form></div>`;
$('#m form').onsubmit=e=>{e.preventDefault();if(save(Object.fromEntries(new FormData(e.target)))!==false)closeM()};$('#m input:not([readonly]),#m select')?.focus()}
function confirmDel(msg,fn){$('#m').innerHTML=`<div class="ov"><div class="md" style="width:min(420px,100%)"><h3>Confirm delete</h3><p>${msg}</p><div class="ft"><button class="b g" onclick="closeM()">Cancel</button><button class="b p" style="background:#b4231f;border-color:#b4231f" id="cd">Delete</button></div></div></div>`;$('#cd').onclick=()=>{fn();closeM()}}
const opts={st:()=>[...db.student].reverse().map(s=>[s.student_id,`${s.name} (${s.student_id})`]),ho:()=>db.hostel.map(h=>[h.hostel_id,`${h.name} (${h.hostel_id})`])};
const tbl=(h,r)=>`<div class="tw"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r||`<tr><td colspan="${h.length}" class="empty">No records found</td></tr>`}</tbody></table></div>`;
const head=(t,s,btn)=>`<div class="ph"><div><h1>${t}</h1><p>${s}</p></div>${btn||''}</div>`;
const addB=(l,f)=>`<button class="b p" onclick="${f}">${ic('plus')}${l}</button>`;
let page='dash',F={q:'',h:'',t:'',s:''};
/* ---------- Pages ---------- */
const P={
dash(){const rooms=db.room,av=rooms.filter(r=>r.status=='Available').length,oc=rooms.filter(r=>r.status=='Occupied').length,mt=rooms.length-av-oc;
const S=[['students','Total Students',db.student.length],['hostels','Total Hostels',db.hostel.length],['rooms','Total Rooms',rooms.length],['bed','Available Rooms',av],['allocations','Occupied Rooms',oc],['pay','Pending Payments',db.payment.filter(p=>p.status=='Pending').length],['complaints','Pending Complaints',db.complaint.filter(c=>c.status=='Pending').length]];
const pct=Math.round(oc/(oc+av||1)*100);
return hero()+`<div class="cards">${S.map(s=>`<div class="card stat"><i>${ic(s[0])}</i><div><b>${s[2]}</b><span>${s[1]}</span></div></div>`).join('')}</div>
<div class="grid2"><div class="card"><h3>Recent Allocations</h3>${tbl(['Student Name','Student ID','Hostel','Room','Allocation Date','Status'],[...db.allocation].reverse().slice(0,5).map(a=>{const r=A('room','room_id',a.room_id);return`<tr><td>${esc(sn(a.student_id))}</td><td>${a.student_id}</td><td>${esc(A('hostel','hostel_id',r.hostel_id).name)}</td><td>${r.room_no}</td><td>${fmt(a.alloc_date)}</td><td>${bg(a.status)}</td></tr>`}).join(''))}</div>
<div class="card"><h3>Hostel Occupancy</h3><div class="donut" style="background:conic-gradient(var(--navy) 0 ${pct}%,#9db3e6 0)"><div><b style="font-size:22px">${pct}%</b><span style="color:var(--mut);font-size:12px">rooms full</span></div></div>
<div class="lg"><span><i style="background:var(--navy)"></i>Occupied ${oc}</span><span><i style="background:#9db3e6"></i>Available ${av}</span>${mt?`<span>Maintenance ${mt}</span>`:''}</div></div></div>
<div class="card"><h3>Recent Complaints</h3>${tbl(['Student','Complaint Type','Date','Status'],[...db.complaint].reverse().slice(0,5).map(c=>`<tr><td>${esc(sn(c.student_id))}</td><td>${c.type}</td><td>${fmt(c.date)}</td><td>${bg(c.status)}</td></tr>`).join(''))}</div>`},
students(){return head('Students',`Table <code>STUDENT</code> · 1:N to ALLOCATION, PAYMENT, COMPLAINT`,addB('Add Student','stuForm()'))+`<div class="card"><div class="bar"><input id="q" placeholder="Search by ID, name, course or department" value="${esc(F.q)}" oninput="F.q=this.value;$('#sb').innerHTML=stuRows()"></div>${tbl(['Student ID','Name','Gender','Phone','Email','Course','Year','Department','Actions'],'<tbody id="sb-x"></tbody>').replace('<tbody><tbody id="sb-x"></tbody>','<tbody id="sb">'+stuRows()).replace('</tbody></tbody>','</tbody>')}</div>`},
hostels(){return head('Hostels',`Table <code>HOSTEL</code> · 1:N to ROOM and SERVICE`,addB('Add Hostel','hosForm()'))+`<div class="card">${tbl(['Hostel ID','Hostel Name','Location','Warden Name','Capacity','Occupied','Available'],db.hostel.map(h=>{const o=hocc(h.hostel_id);return`<tr><td>${h.hostel_id}</td><td><b>${esc(h.name)}</b></td><td>${esc(h.location)}</td><td>${esc(h.warden)}</td><td>${h.capacity}</td><td><div class="pb"><i style="width:${Math.min(100,o/h.capacity*100)}%"></i></div>${o}</td><td>${h.capacity-o}</td></tr>`}).join(''))}</div>`},
rooms(){const L=db.room.filter(r=>(!F.h||r.hostel_id==F.h)&&(!F.t||r.type==F.t)&&(!F.s||r.status==F.s)),sel=(k,l,o)=>`<select onchange="F.${k}=this.value;render()"><option value="">${l}</option>${o.map(x=>{const[a,b]=Array.isArray(x)?x:[x,x];return`<option value="${a}" ${F[k]==a?'selected':''}>${esc(b)}</option>`}).join('')}</select>`;
return head('Rooms',`Table <code>ROOM</code> · FK hostel_id → HOSTEL`,addB('Add Room','roomForm()'))+`<div class="card"><div class="bar">${sel('h','All hostels',opts.ho())}${sel('t','All room types',['Single','Double','Triple'])}${sel('s','All statuses',['Available','Occupied','Maintenance'])}</div>${tbl(['Room ID','Hostel','Room Number','Room Type','Capacity','Occupancy','Status'],L.map(r=>`<tr><td>${r.room_id}</td><td>${esc(A('hostel','hostel_id',r.hostel_id).name)}</td><td>${r.room_no}</td><td>${r.type}</td><td>${r.capacity}</td><td>${occ(r.room_id)}/${r.capacity}</td><td>${bg(r.status)}</td></tr>`).join(''))}</div>`},
allocations(){return head('Allocations',`Table <code>ALLOCATION</code> · FK student_id → STUDENT, room_id → ROOM`,addB('New Allocation','allocForm()'))+`<div class="card">${tbl(['Allocation ID','Student','Student ID','Hostel','Room','Allocation Date','End Date','Status'],[...db.allocation].reverse().map(a=>{const r=A('room','room_id',a.room_id);return`<tr><td>${a.alloc_id}</td><td>${esc(sn(a.student_id))}</td><td>${a.student_id}</td><td>${esc(A('hostel','hostel_id',r.hostel_id).name)}</td><td>${r.room_no}</td><td>${fmt(a.alloc_date)}</td><td>${fmt(a.end_date)}</td><td>${bg(a.status)}</td></tr>`}).join(''))}</div>`},
payments(){const p=db.payment,paid=p.filter(x=>x.status=='Paid');
return head('Payments',`Table <code>PAYMENT</code> · FK student_id → STUDENT`,addB('Record Payment','payForm()'))+`<div class="cards">${[['Total Payments',p.length],['Completed',paid.length],['Pending',p.filter(x=>x.status=='Pending').length],['Total Amount',money(paid.reduce((s,x)=>s+ +x.amount,0))]].map(c=>`<div class="card stat"><div><b>${c[1]}</b><span>${c[0]}</span></div></div>`).join('')}</div><div class="card">${tbl(['Payment ID','Student','Student ID','Amount','Payment Date','Payment Mode','Payment Status'],[...p].reverse().map(x=>`<tr><td>${x.payment_id}</td><td>${esc(sn(x.student_id))}</td><td>${x.student_id}</td><td>${money(x.amount)}</td><td>${fmt(x.date)}</td><td>${x.mode}</td><td>${bg(x.status)}</td></tr>`).join(''))}</div>`},
complaints(){return head('Complaints',`Table <code>COMPLAINT</code> · FK student_id → STUDENT`,addB('Register Complaint','compForm()'))+`<div class="card">${tbl(['Complaint ID','Student','Complaint Type','Description','Complaint Date','Status','Actions'],[...db.complaint].reverse().map(c=>`<tr><td>${c.complaint_id}</td><td>${esc(sn(c.student_id))}</td><td>${c.type}</td><td class="wrap">${esc(c.description)}</td><td>${fmt(c.date)}</td><td>${bg(c.status)}</td><td><select class="cs" aria-label="Change status" onchange="setC('${c.complaint_id}',this.value)">${['Pending','In Progress','Resolved'].map(s=>`<option ${s==c.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join(''))}</div>`},
services(){return head('Services',`Table <code>SERVICE</code> · FK hostel_id → HOSTEL`,addB('Add Service','svcForm()'))+`<div class="card">${tbl(['Service ID','Hostel','Service Name','Description','Availability Status'],db.service.map(s=>`<tr><td>${s.service_id}</td><td>${esc(A('hostel','hostel_id',s.hostel_id).name)}</td><td><b>${esc(s.name)}</b></td><td>${esc(s.description)}</td><td>${bg(s.available)}</td></tr>`).join(''))}</div>`},
stu(id){const s=A('student','student_id',id);if(!s)return P.students();
const al=db.allocation.filter(a=>a.student_id==id&&a.status=='Active').pop(),r=al&&A('room','room_id',al.room_id),py=db.payment.filter(p=>p.student_id==id),paid=py.filter(p=>p.status=='Paid').reduce((x,p)=>x+ +p.amount,0),pend=py.filter(p=>p.status=='Pending').reduce((x,p)=>x+ +p.amount,0),cs=db.complaint.filter(c=>c.student_id==id);
const kv=o=>`<dl class="kv">${o.map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl>`;
return head(esc(s.name),`Student profile · ${s.student_id}`,`<div class="act"><button class="b" onclick="go('students')">${ic('back')}Back</button><button class="b" onclick="stuForm('${id}')">${ic('edit')}Edit</button></div>`)+`<div class="grid2b"><div class="card"><h3>Student Information</h3>${kv([['Student ID',s.student_id],['Name',esc(s.name)],['Gender',s.gender],['Phone',s.phone],['Email',esc(s.email)],['Course',esc(s.course)],['Year',s.year],['Department',esc(s.department)]])}</div>
<div><div class="card" style="margin-bottom:16px"><h3>Current Accommodation</h3>${r?kv([['Hostel',esc(A('hostel','hostel_id',r.hostel_id).name)],['Room',r.room_no],['Room Type',r.type],['Allocation Date',fmt(al.alloc_date)]]):'<div class="empty">No active allocation yet. Use Allocations → New Allocation.</div>'}</div>
<div class="card"><h3>Payment Summary</h3>${py.length?kv([['Total Paid',money(paid)],['Pending Amount',money(pend)],['Payment Status',bg(pend?'Pending':'Paid')]]):'<div class="empty">No payments recorded yet.</div>'}</div></div></div>
<div class="card" style="margin-top:16px"><h3>Complaints</h3>${tbl(['ID','Type','Description','Date','Status'],cs.map(c=>`<tr><td>${c.complaint_id}</td><td>${c.type}</td><td class="wrap">${esc(c.description)}</td><td>${fmt(c.date)}</td><td>${bg(c.status)}</td></tr>`).join(''))}</div>`}};
function stuRows(){const q=F.q.toLowerCase();return db.student.filter(s=>Object.values(s).join(' ').toLowerCase().includes(q)).map(s=>`<tr><td>${s.student_id}</td><td><b>${esc(s.name)}</b></td><td>${s.gender}</td><td>${s.phone}</td><td>${esc(s.email)}</td><td>${esc(s.course)}</td><td>${s.year}</td><td>${esc(s.department)}</td><td><div class="act"><button class="b s" title="View" aria-label="View" onclick="go('stu:${s.student_id}')">${ic('eye')}</button><button class="b s" title="Edit" aria-label="Edit" onclick="stuForm('${s.student_id}')">${ic('edit')}</button><button class="b s d" title="Delete" aria-label="Delete" onclick="delStu('${s.student_id}')">${ic('trash')}</button></div></td></tr>`).join('')||`<tr><td colspan="9" class="empty">No students match your search</td></tr>`}
/* ---------- Forms & actions ---------- */
function stuForm(id){const e=id&&A('student','student_id',id);
modal(e?'Edit Student':'Add Student',[{n:'student_id',l:'Student ID',d:'STU2026',ro:!!e},{n:'name',l:'Name'},{n:'gender',l:'Gender',t:'select',o:['Male','Female','Other']},{n:'phone',l:'Phone',t:'tel'},{n:'email',l:'Email',t:'email',w:1},{n:'course',l:'Course'},{n:'year',l:'Year',t:'select',o:['1','2','3','4']},{n:'department',l:'Department',w:1}],e,e?'Save Changes':'Add Student',d=>{
if(e){Object.assign(e,d);toast('Student updated');}else{if(A('student','student_id',d.student_id)){toast('Student ID already exists (primary key)',1);return false}db.student.push(d);toast('Student added successfully')}render()})}
function delStu(id){confirmDel(`Delete <b>${esc(sn(id))}</b>? Their allocations, payments and complaints are removed too (ON DELETE CASCADE).`,()=>{const rs=db.allocation.filter(a=>a.student_id==id).map(a=>a.room_id);
['allocation','payment','complaint'].forEach(t=>db[t]=db[t].filter(x=>x.student_id!=id));db.student=db.student.filter(s=>s.student_id!=id);rs.forEach(sync);toast('Student deleted');render()})}
const hosForm=()=>modal('Add Hostel',[{n:'hostel_id',l:'Hostel ID',d:nid('hostel','hostel_id','H',2)},{n:'name',l:'Hostel Name'},{n:'location',l:'Location'},{n:'warden',l:'Warden Name'},{n:'capacity',l:'Capacity',t:'number',w:1}],null,'Add Hostel',d=>{if(A('hostel','hostel_id',d.hostel_id)){toast('Hostel ID already exists',1);return false}d.capacity=+d.capacity;db.hostel.push(d);toast('Hostel added successfully');render()});
const roomForm=()=>modal('Add Room',[{n:'hostel_id',l:'Hostel',t:'select',o:opts.ho(),w:1},{n:'room_no',l:'Room Number'},{n:'type',l:'Room Type',t:'select',o:['Single','Double','Triple']},{n:'capacity',l:'Capacity',t:'number',d:1},{n:'status',l:'Status',t:'select',o:['Available','Maintenance']}],null,'Add Room',d=>{d.room_id=nid('room','room_id','R');d.capacity=+d.capacity;db.room.push(d);toast('Room added successfully');render()});
function roomOpts(h){return db.room.filter(r=>r.hostel_id==h&&r.status=='Available').map(r=>[r.room_id,`Room ${r.room_no} · ${r.type} (${occ(r.room_id)}/${r.capacity})`])}
function allocForm(){const free=opts.st().filter(([id])=>!db.allocation.some(a=>a.student_id==id&&a.status=='Active')),h0=db.hostel[0].hostel_id;
modal('New Allocation',[{n:'student_id',l:'Student',t:'select',o:free.length?free:opts.st(),w:1},{n:'hostel_id',l:'Hostel',t:'select',o:opts.ho(),ch:"upRooms(this.value)"},{n:'room_id',l:'Room',t:'select',o:roomOpts(h0).length?roomOpts(h0):[['','No available rooms']]},{n:'alloc_date',l:'Allocation Date',t:'date',d:today()},{n:'end_date',l:'End Date',t:'date',d:'2027-05-31'},{n:'status',l:'Status',t:'select',o:['Active','Reserved','Completed'],w:1}],null,'Allocate Room',d=>{
if(!d.room_id){toast('Choose a hostel that has an available room',1);return false}
if(d.end_date<d.alloc_date){toast('End date must be after allocation date',1);return false}
if(d.status=='Active'&&db.allocation.some(a=>a.student_id==d.student_id&&a.status=='Active')){toast('Student already has an active allocation',1);return false}
db.allocation.push({alloc_id:nid('allocation','alloc_id','A'),student_id:d.student_id,room_id:d.room_id,alloc_date:d.alloc_date,end_date:d.end_date,status:d.status});sync(d.room_id);toast(`Room allocated · ${sn(d.student_id)} → Room ${A('room','room_id',d.room_id).room_no}`);go('allocations')})}
function upRooms(h){const o=roomOpts(h),s=$('#m select[name=room_id]');s.innerHTML=o.length?o.map(([a,b])=>`<option value="${a}">${esc(b)}</option>`).join(''):'<option value="">No available rooms</option>'}
const payForm=()=>modal('Record Payment',[{n:'student_id',l:'Student',t:'select',o:opts.st(),w:1},{n:'amount',l:'Amount (₹)',t:'number',d:45000},{n:'date',l:'Payment Date',t:'date',d:today()},{n:'mode',l:'Payment Mode',t:'select',o:['UPI','Cash','Card','Net Banking']},{n:'status',l:'Payment Status',t:'select',o:['Paid','Pending','Failed']}],null,'Record Payment',d=>{d.payment_id=nid('payment','payment_id','P');d.amount=+d.amount;db.payment.push(d);toast('Payment recorded successfully');render()});
const compForm=()=>modal('Register Complaint',[{n:'student_id',l:'Student',t:'select',o:opts.st(),w:1},{n:'type',l:'Complaint Type',t:'select',o:['Maintenance','Electrical','Plumbing','Cleanliness','Noise','Internet']},{n:'date',l:'Date',t:'date',d:today()},{n:'description',l:'Description',t:'textarea',w:1},{n:'status',l:'Status',t:'select',o:['Pending','In Progress','Resolved'],w:1}],null,'Register Complaint',d=>{d.complaint_id=nid('complaint','complaint_id','C');db.complaint.push(d);toast('Complaint registered');render()});
const svcForm=()=>modal('Add Service',[{n:'hostel_id',l:'Hostel',t:'select',o:opts.ho()},{n:'name',l:'Service Name',t:'select',o:['Laundry','Wi-Fi','Housekeeping','Maintenance','Drinking Water','Gym']},{n:'description',l:'Description',w:1},{n:'available',l:'Availability',t:'select',o:['Available','Unavailable'],w:1}],null,'Add Service',d=>{d.service_id=nid('service','service_id','SV');db.service.push(d);toast('Service added successfully');render()});
function setC(id,s){A('complaint','complaint_id',id).status=s;toast(`Complaint ${id} marked ${s}`);render()}
/* ---------- Shell ---------- */
const NAV=[['dash','Dashboard'],['students','Students'],['hostels','Hostels'],['rooms','Rooms'],['allocations','Allocations'],['payments','Payments'],['complaints','Complaints'],['services','Services']];
$('#lg').innerHTML=ic('hostels');
$('#nav').innerHTML=NAV.map(([k,l])=>`<button data-p="${k}" onclick="go('${k}')">${ic(k)}${l}</button>`).join('');
function go(p){page=p;F={q:'',h:'',t:'',s:''};render()}
function render(){const[k,a]=page.split(':');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.p==(k=='stu'?'students':k)));$('#main').innerHTML=P[k](a)}
render();
function hero(){const n=db.student.length,o=db.allocation.filter(a=>a.status=='Active').length,h=new Date().getHours();
return `<section class="hero"><div><span class="eyebrow">${h<12?'Good morning':h<17?'Good afternoon':'Good evening'}, Warden</span><h1>Every student, room and request in one place.</h1><p>${n} students registered, ${o} active allocations across ${db.hostel.length} hostels.</p></div><div class="hero-cta"><button class="b" onclick="go('students')">${ic('students')}Manage students</button><button class="b" onclick="allocForm()">${ic('allocations')}New allocation</button></div></section>`}